### ISSUE TITLE
index out of range if trying to open a shell over an empty result

### ISSUE THREAD

**Issue by mangelajo** [mangelajo/track#3]
mbp-ajo:track ajo$ ./track bz-list --me -x --shell **--changed**
1546994 (    POST)	majopela@redhat.com	https://bugzilla.redhat.com/1546994	python-networking-ovn	[RFE] [Neutron] [OVN] Productize a migration tool from ML2/OVS to OVN
1575706 (VERIFIED)	majopela@redhat.com	https://bugzilla.redhat.com/1575706	   openstack-neutron	Neutron agents attach untagged ports to br-int, which will be trunk port if neutron-openvswitch-agent never handles them
1581332 (    POST)	majopela@redhat.com	https://bugzilla.redhat.com/1581332	python-networking-ovn	Internal DNS resolution does not work for fqdn
1570843 (ASSIGNED)	majopela@redhat.com	https://bugzilla.redhat.com/1570843	python-networking-ovn	East/West traffic goes through controller node on DVR-VLAN deployment
1546996 (     NEW)	majopela@redhat.com	https://bugzilla.redhat.com/1546996	python-networking-ovn	[RFE] [Neutron] [OVN] QoS support
1579300 (VERIFIED)	majopela@redhat.com	https://bugzilla.redhat.com/1579300	     python-ovsdbapp	neutron-openvswitch-agent eventually fails listing high count of ports on network node.
1399987 (ASSIGNED)	majopela@redhat.com	https://bugzilla.redhat.com/1399987	   openstack-neutron	[RFE] allow to limit conntrack entries per tenant to avoid "nf_conntrack: table full, dropping packet"
1503502 (VERIFIED)	majopela@redhat.com	https://bugzilla.redhat.com/1503502	python-networking-ovn	[RFE] [Neutron] [OVN] DVR support
1433532 (VERIFIED)	majopela@redhat.com	https://bugzilla.redhat.com/1433532	         openvswitch	[RFE] [Neutron] [OVN] L3 HA
Grabbing bug details: done.
Pre caching HTML: bz#1546994 bz#1433532 bz#1503502 bz#1579300 done.

9 bugs found.

Track interactive shell
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/mangelajo/track/pkg/shell.Shell(0xc4203562c0, 0x15286c8)
	/Users/ajo/go/src/github.com/mangelajo/track/pkg/shell/shell.go:29 +0x14f2
github.com/mangelajo/track/cmd.listBugs(0xc420524600, 0x9, 0x9, 0xc4200cc960)
	/Users/ajo/go/src/github.com/mangelajo/track/cmd/bzList.go:146 +0x63e
github.com/mangelajo/track/cmd.bzList(0x17c2b20, 0xc4200be680, 0x0, 0x4)
	/Users/ajo/go/src/github.com/mangelajo/track/cmd/bzList.go:111 +0x252
github.com/mangelajo/track/vendor/github.com/spf13/cobra.(*Command).execute(0x17c2b20, 0xc4200be600, 0x4, 0x4, 0x17c2b20, 0xc4200be600)
	/Users/ajo/go/src/github.com/mangelajo/track/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/mangelajo/track/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x17c34a0, 0x14, 0xc4200dc300, 0x14)
	/Users/ajo/go/src/github.com/mangelajo/track/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/mangelajo/track/vendor/github.com/spf13/cobra.(*Command).Execute(0x17c34a0, 0xc420189f20, 0x1160d5f)
	/Users/ajo/go/src/github.com/mangelajo/track/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/mangelajo/track/cmd.Execute()
	/Users/ajo/go/src/github.com/mangelajo/track/cmd/root.go:53 +0x2d
main.main()
	/Users/ajo/go/src/github.com/mangelajo/track/main.go:29 +0x98

**Comment by mangelajo** [comment]
Fixed in 78a761bc66e2520aa7bb4bac0705418e24061ea9
